baseURL = "https://hospicjum.onrender.com"
disableLanguages = []
disqusShortname = "viadrus"
paginate = "4"
summaryLength = "10"
theme = "vixcon-hugo"
title = "Hospicjum dla zwierząt Stowarzyszenia W Ogrodzie Viadrusa"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 Stowarzyszenie w Ogrodzie Viadrusa"
footer_content = "Lorem ipsum"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
hasChildren = true
URL = "about"
name = "O nas"
weight = 1
[[menu.main]]
URL = "hospicjum_dla_zwierzat"
name = "Hospicjum dla zwierząt"
weight = 3
[[menu.main]]
URL = "kontakt"
name = "Kontakt"
weight = 6
# [[menu.main]]
# hasChildren = true
# name = "Pages"
# weight = 5
[[menu.main]]
URL = "about"
name = "Działalność lokalna"
weight = 4
[[menu.main]]
URL = "warsztaty"
name = "Warsztaty"
parent = "Działalność lokalna"
weight = 1
[[menu.main]]
URL = "projekty"
name = "Projekty"
parent = "Działalność lokalna"
weight = 2
[[menu.main]]
URL = "dzialania_ekologiczne"
name = "Działania ekologiczne"
parent = "Działalność lokalna"
weight = 3
[[menu.main]]
URL = "blog"
name = "Aktualności"
weight = 2
[[menu.main]]
URL = "media_o_nas"
name = "Media o nas"
parent = "O nas"
weight = 4
# [[menu.main]]
# URL = "faq"
# name = "FAQ"
# parent = "Pages"
# weight = 4
[[menu.main]]
URL = "historia_powstania"
name = "Historia powstania"
parent = "O nas"
weight = 1
# [[menu.main]]
# URL = "pricing"
# name = "Tickets"
# parent = "Pages"
# weight = 1
[[menu.main]]
URL = "statut_i_inne_dokumenty"
name = "Statut i inne dokumenty"
parent = "O nas"
weight = 2
# [[menu.main]]
# URL = "blog"
# name = "Blog"
# parent = "Pages"
# weight = 2
# [[menu.main]]
# URL = "schedule"
# name = "Schedule"
# parent = "Pages"
# weight = 3
[[menu.main]]
URL = "wsparli_nas"
name = "Wsparli nas"
parent = "O nas"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Stowarzyszenie W Ogrodzie Viadrusa"
contact_form_action = "https://formspree.io/f/mdoyrlny"
description = "Hospicjum dla zwierząt Stowarzyszenia W Ogrodzie Viadrusa"
email = "demo@vixcon.com"
dateFormat = "02 Jan 2006"
google_analitycs_id = ""
home = "Home"
logo = "uploads/logo_stowarzyszenie_viadrusa.png"
search = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCtJrYWACnKLdhpfql7pky42O26qSY3QCc"
map_latitude = "50.718455812025105"
map_longitude = "17.615895678419783"
map_marker = "images/marker.png"
[params.navigation_button]
enable = true
label = "Jak nam pomóc"
link = "jak_nam_pomoc"
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = ""
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us20.list-manage.com/subscribe/post?u=e7a51a412128117933d864ff9&amp;id=3240521bd7"
mailchimp_form_name = "mc-embedded-subscribe-form"
[[params.social]]
icon = "tf-ion-social-facebook"
link = "https://www.facebook.com/WOgrodzieViadrusa/"
