baseURL = "https://examplesite.org"
disableLanguages = []
disqusShortname = "vixcon"
paginate = "4"
summaryLength = "10"
theme = "vixcon-hugo"
title = "Vixcon"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 Stowarzyszenie w Ogrodzie Viadrusa"
footer_content = "We are a creative-led experiential Event Production Agency that helps brands connect, engage and evolve."
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "about"
name = "O nas"
weight = 1
[[menu.main]]
URL = "hospicjum_dla_zwierzat"
name = "Hospicjum dla zwierząt"
weight = 3
[[menu.main]]
URL = "contact"
name = "Kontakt"
weight = 6
[[menu.main]]
hasChildren = true
name = "Pages"
weight = 5
[[menu.main]]
URL = "about"
name = "Działalność lokalna"
weight = 4
[[menu.main]]
URL = "blog"
name = "Aktualności"
weight = 2
[[menu.main]]
URL = "media_o_nas"
name = "Media o nas"
parent = "O nas"
weight = 4
[[menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
weight = 4
[[menu.main]]
URL = "historia_powstania"
name = "Historia powstania"
parent = "O nas"
weight = 1
[[menu.main]]
URL = "pricing"
name = "Tickets"
parent = "Pages"
weight = 1
[[menu.main]]
URL = "statut_i_inne_dokumenty"
name = "Statut i inne dokumenty"
parent = "O nas"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
parent = "Pages"
weight = 2
[[menu.main]]
URL = "schedule"
name = "Schedule"
parent = "Pages"
weight = 3
[[menu.main]]
URL = "wspieraja_nas"
name = "Wspierają nas"
parent = "O nas"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
email = "demo@vixcon.com"
google_analitycs_id = ""
home = "Home"
logo = "uploads/logo_stowarzyszenie_viadrusa.png"
search = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.navigation_button]
enable = true
label = "Jak nam pomóc"
link = "pricing"
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = ""
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "tf-ion-social-facebook"
link = "#"
[[params.social]]
icon = "tf-ion-social-twitter"
link = "#"
[[params.social]]
icon = "tf-ion-social-linkedin"
link = "#"
[[params.social]]
icon = "tf-ion-social-pinterest"
link = "#"
[[params.social]]
icon = "tf-ion-social-rss"
link = "#"
